"""
RAG Retriever
==============
Retrieves relevant passages from the vector store to ground SLM outputs.

Documents indexed:
- Official curriculum / syllabus (NEET/JEE)
- Historical exam patterns (year-wise topic data)
- Chapter/topic taxonomy
- Revision playbooks
- Benchmark blueprints
- Historical insights generated by this system

Retrieval pipeline:
1. Build a rich query from the request context
2. Filter by metadata (exam_type, subject, chapter)
3. Dense retrieval from vector store
4. Rerank by combined relevance + recency
5. Return top-K passages
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class RAGRetriever:
    """
    Abstract retriever. Backed by ChromaDB (default), but swappable.
    """

    def __init__(
        self,
        collection_name:  str  = "prajna_rag",
        persist_dir:      str  = "./data/rag_store",
        embedding_model:  str  = "all-MiniLM-L6-v2",   # same model as PRAJNA SLM!
        top_k_fetch:      int  = 20,   # fetch more, rerank to top_k
        rerank_enabled:   bool = True,
    ):
        self.collection_name = collection_name
        self.persist_dir     = persist_dir
        self.embedding_model = embedding_model
        self.top_k_fetch     = top_k_fetch
        self.rerank_enabled  = rerank_enabled
        self._client         = None
        self._collection     = None
        self._embedder       = None

    # ── Initialization ─────────────────────────────────────────────────────────

    def _init_client(self):
        if self._client is not None:
            return
        try:
            import chromadb
            from chromadb.config import Settings
            self._client = chromadb.PersistentClient(
                path=self.persist_dir,
                settings=Settings(anonymized_telemetry=False),
            )
            self._collection = self._client.get_or_create_collection(
                name=self.collection_name,
                metadata={"hnsw:space": "cosine"},
            )
            logger.info(f"ChromaDB initialized: {self.collection_name} "
                        f"({self._collection.count()} docs)")
        except ImportError:
            logger.warning("ChromaDB not installed. RAG retrieval will return empty results.")
            logger.warning("Install with: pip install chromadb")
            self._client = "unavailable"

    def _get_embedder(self):
        if self._embedder is not None:
            return self._embedder
        try:
            from sentence_transformers import SentenceTransformer
            # Reuse the same embedding model as PRAJNA SLM for consistency
            self._embedder = SentenceTransformer(self.embedding_model)
            logger.info(f"Embedder loaded: {self.embedding_model}")
        except ImportError:
            logger.warning("sentence_transformers not available")
            self._embedder = None
        return self._embedder

    # ── Public API ─────────────────────────────────────────────────────────────

    async def retrieve(
        self,
        query: str,
        exam_type: Optional[str] = None,
        subject: Optional[str] = None,
        chapter: Optional[str] = None,
        top_k: int = 5,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve relevant passages for a query.
        Returns list of dicts: {id, text, source, score, metadata, evidence_type}
        """
        import asyncio
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            self._retrieve_sync,
            query, exam_type, subject, chapter, top_k,
        )

    def _retrieve_sync(
        self,
        query: str,
        exam_type: Optional[str],
        subject: Optional[str],
        chapter: Optional[str],
        top_k: int,
    ) -> List[Dict[str, Any]]:
        self._init_client()
        if self._client == "unavailable":
            return []

        embedder = self._get_embedder()
        if embedder is None:
            return []

        # Build enriched query
        enriched_query = self._enrich_query(query, exam_type, subject, chapter)
        query_embedding = embedder.encode(enriched_query).tolist()

        # Build metadata filter
        where_filter = self._build_filter(exam_type, subject, chapter)

        try:
            results = self._collection.query(
                query_embeddings=[query_embedding],
                n_results=min(self.top_k_fetch, self._collection.count() or 1),
                where=where_filter if where_filter else None,
                include=["documents", "metadatas", "distances"],
            )
        except Exception as e:
            logger.error(f"ChromaDB query failed: {e}")
            return []

        # Convert to flat list
        passages = []
        docs       = results.get("documents",  [[]])[0]
        metas      = results.get("metadatas",  [[]])[0]
        distances  = results.get("distances",  [[]])[0]
        ids        = results.get("ids",        [[]])[0]

        for doc_id, text, meta, dist in zip(ids, docs, metas, distances):
            # ChromaDB returns cosine distance (lower=better), convert to similarity
            score = 1.0 - float(dist)
            passages.append({
                "id":            doc_id,
                "text":          text,
                "source":        meta.get("source", "Unknown"),
                "evidence_type": meta.get("evidence_type", "retrieved_chunk"),
                "subject":       meta.get("subject"),
                "chapter":       meta.get("chapter"),
                "exam_type":     meta.get("exam_type"),
                "year":          meta.get("year"),
                "score":         round(score, 4),
                **{k: v for k, v in meta.items()
                   if k not in ("source", "evidence_type", "subject", "chapter", "exam_type", "year")},
            })

        # Rerank if enabled
        if self.rerank_enabled and passages:
            passages = self._rerank(passages, query)

        return passages[:top_k]

    # ── Reranking ──────────────────────────────────────────────────────────────

    def _rerank(
        self, passages: List[Dict], query: str
    ) -> List[Dict]:
        """
        Rerank passages by combined:
        - Semantic similarity score
        - Recency (more recent exam years rank higher)
        - Evidence type weight (prediction_signal > historical_exam > curriculum)
        """
        EVIDENCE_WEIGHTS = {
            "prediction_signal":    1.20,
            "historical_exam":      1.10,
            "curriculum_doc":       1.05,
            "benchmark_pattern":    1.00,
            "retrieved_chunk":      0.95,
            "student_performance":  0.85,
        }

        import datetime
        current_year = datetime.datetime.utcnow().year

        for p in passages:
            base_score  = p.get("score", 0.5)
            ev_weight   = EVIDENCE_WEIGHTS.get(p.get("evidence_type", "retrieved_chunk"), 1.0)

            # Recency bonus: exponential decay on year gap
            year = p.get("year")
            recency = 1.0
            if year:
                gap = current_year - int(year)
                recency = max(0.7, 1.0 - 0.05 * gap)

            p["rerank_score"] = base_score * ev_weight * recency

        passages.sort(key=lambda p: p["rerank_score"], reverse=True)
        return passages

    # ── Helpers ────────────────────────────────────────────────────────────────

    @staticmethod
    def _enrich_query(
        query: str,
        exam_type: Optional[str],
        subject: Optional[str],
        chapter: Optional[str],
    ) -> str:
        """Enrich the query with context terms to improve retrieval."""
        parts = [query]
        if exam_type:  parts.append(exam_type)
        if subject:    parts.append(subject)
        if chapter:    parts.append(chapter)
        return " ".join(parts)

    @staticmethod
    def _build_filter(
        exam_type: Optional[str],
        subject: Optional[str],
        chapter: Optional[str],
    ) -> Optional[Dict]:
        """Build ChromaDB metadata filter."""
        conditions = []
        if exam_type:
            conditions.append({"exam_type": {"$eq": exam_type}})
        if subject:
            conditions.append({"subject": {"$eq": subject}})
        if chapter:
            conditions.append({"chapter": {"$eq": chapter}})

        if not conditions:
            return None
        if len(conditions) == 1:
            return conditions[0]
        return {"$and": conditions}
