"""
Intelligence Layer Schemas
============================
Internal objects produced by the Topic Intelligence Aggregator, Ranker,
Cluster Detector, and Trend Analyzer.  These are the structured inputs
to the SLM Insight Engine.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from .prediction import (
    AppearancePattern, ExamType, HierarchyScope,
    TrendDirection, WeightageBand,
)


# ── Revision Priority ─────────────────────────────────────────────────────────

class RevisionUrgency(str, Enum):
    CRITICAL   = "critical"    # Must revise — very high exam weight + strong signal
    HIGH       = "high"
    MEDIUM     = "medium"
    LOW        = "low"
    OPTIONAL   = "optional"    # Low probability but may cluster with high-priority topics


class RevisionPriorityObject(BaseModel):
    """
    A single topic/chapter/micro_topic ranked for revision priority.
    Produced by the Ranker pipeline.
    """
    scope:        HierarchyScope
    scope_name:   str
    parent_chain: List[str] = Field(
        description="[subject, chapter, topic] — from root to item"
    )
    exam_type:    ExamType
    target_year:  int

    urgency:           RevisionUrgency
    priority_score:    float = Field(ge=0.0, le=100.0,
        description="Composite priority score 0–100")
    importance_probability: float = Field(ge=0.0, le=1.0)
    confidence:        float = Field(ge=0.0, le=1.0)
    expected_weightage_band: WeightageBand
    trend_direction:   TrendDirection

    # Explanatory signals
    key_reasons:       List[str] = Field(default_factory=list,
        description="Top 3 reasons for this priority, in plain language")
    risk_if_skipped:   str  = ""   # e.g. "Likely 3–4 marks impact"
    estimated_study_hours: Optional[float] = None

    ranked_at: datetime = Field(default_factory=datetime.utcnow)


# ── Evidence / Citation ───────────────────────────────────────────────────────

class EvidenceType(str, Enum):
    PREDICTION_SIGNAL   = "prediction_signal"   # from PRAJNA SLM output
    HISTORICAL_EXAM     = "historical_exam"     # from past exam records
    CURRICULUM_DOC      = "curriculum_doc"      # official syllabus/blueprint
    BENCHMARK_PATTERN   = "benchmark_pattern"   # external benchmark data
    RETRIEVED_CHUNK     = "retrieved_chunk"     # RAG-retrieved passage
    STUDENT_PERFORMANCE = "student_performance" # from student mock data


class EvidenceObject(BaseModel):
    """Traceable evidence item cited by an insight."""
    evidence_id:   str
    evidence_type: EvidenceType
    source_name:   str    # e.g. "NEET 2024 Question Paper" or "PRAJNA SLM v3"
    source_url:    Optional[str] = None
    excerpt:       str   = Field(description="Relevant snippet (max 500 chars)")
    relevance_score: float = Field(ge=0.0, le=1.0)
    metadata:      Dict[str, Any] = Field(default_factory=dict)


# ── Insight Object ─────────────────────────────────────────────────────────────

class InsightType(str, Enum):
    TOPIC_IMPORTANCE       = "topic_importance"
    TREND_SHIFT            = "trend_shift"
    RECURRING_TOPIC        = "recurring_topic"
    CLUSTER_ALERT          = "cluster_alert"
    REVISION_PRIORITY      = "revision_priority"
    EXAM_STRATEGY          = "exam_strategy"
    CHAPTER_SUMMARY        = "chapter_summary"
    SUBJECT_STRATEGY       = "subject_strategy"
    MICRO_TOPIC_SPOTLIGHT  = "micro_topic_spotlight"
    RISK_ALERT             = "risk_alert"       # topic with high importance + student weakness
    EXAM_BRIEF             = "exam_brief"


class PersonaType(str, Enum):
    STUDENT          = "student"
    TEACHER          = "teacher"
    ACADEMIC_PLANNER = "academic_planner"
    CONTENT_TEAM     = "content_team"
    EXAM_ANALYST     = "exam_analyst"


class InsightObject(BaseModel):
    """
    A single grounded insight generated by the SLM Insight Engine.
    Every insight is traceable to structured evidence.
    """
    insight_id:    str
    insight_type:  InsightType
    persona:       PersonaType

    # Content
    title:         str   = Field(description="Short headline, ≤ 80 chars")
    scope:         HierarchyScope
    scope_name:    str
    parent_chain:  List[str] = Field(default_factory=list)

    claim:         str   = Field(description="The core assertion in 1–2 sentences")
    narrative:     str   = Field(description="Full SLM-generated explanation, 100–400 words")
    recommended_action: str = Field(description="What the persona should do")

    # Grounding
    evidence:      List[EvidenceObject] = Field(default_factory=list)
    confidence:    float = Field(ge=0.0, le=1.0)
    is_grounded:   bool  = True   # False if evidence is thin

    # Supporting metrics (raw numbers for UI rendering)
    supporting_metrics: Dict[str, Any] = Field(default_factory=dict)

    # Persona-specific
    urgency:       Optional[RevisionUrgency] = None
    tags:          List[str] = Field(default_factory=list)

    generated_at:  datetime = Field(default_factory=datetime.utcnow)
    slm_model_id:  str = ""
    prompt_version: str = "v1"


# ── Topic Cluster ──────────────────────────────────────────────────────────────

class TopicClusterObject(BaseModel):
    """
    A cluster of related topics detected by the intelligence layer.
    Topics in a cluster tend to co-occur and share conceptual dependencies.
    """
    cluster_id:     str
    cluster_name:   str
    exam_type:      ExamType
    target_year:    int

    anchor_topic:   str   = Field(description="The highest-importance topic in the cluster")
    member_topics:  List[str]
    member_chapters: List[str]
    subject:        str

    avg_importance:     float = Field(ge=0.0, le=1.0)
    cluster_importance: float = Field(ge=0.0, le=1.0,
        description="Weighted cluster-level importance; higher than any individual member")
    trend_direction:    TrendDirection
    co_occurrence_score: float = Field(ge=0.0, le=1.0,
        description="Historical co-occurrence rate across past exams")

    strategic_note: str = ""   # Why this cluster matters as a unit


# ── Chapter Summary ────────────────────────────────────────────────────────────

class ChapterSummaryObject(BaseModel):
    """Comprehensive chapter-level intelligence summary."""
    chapter:     str
    subject:     str
    exam_type:   ExamType
    target_year: int

    importance_tier: str  = Field(description="A/B/C — A=must revise, C=optional")
    composite_importance:  float
    expected_questions:    str   = Field(description="e.g. '3–5 questions'")
    revision_priority:     RevisionUrgency
    trend_direction:       TrendDirection

    top_priority_topics:   List[RevisionPriorityObject] = Field(default_factory=list)
    key_micro_topics:      List[str] = Field(default_factory=list)
    topic_clusters:        List[TopicClusterObject] = Field(default_factory=list)

    # Narrative outputs (SLM-generated)
    chapter_brief:         str = ""   # 2–3 paragraph chapter importance summary
    teacher_notes:         str = ""   # Notes for teacher
    student_summary:       str = ""   # Student-friendly revision focus

    evidence:              List[EvidenceObject] = Field(default_factory=list)
    confidence:            float = Field(ge=0.0, le=1.0)


# ── Subject Strategy ───────────────────────────────────────────────────────────

class SubjectStrategySummary(BaseModel):
    """
    Subject-level strategic revision plan.
    The highest-level artefact produced by the intelligence layer.
    """
    subject:     str
    exam_type:   ExamType
    target_year: int

    subject_rank:              int    = Field(description="Rank vs other subjects")
    overall_importance:        float  = Field(ge=0.0, le=1.0)
    recommended_study_hours:   float
    expected_marks_coverage:   str   = Field(description="e.g. '38–42 marks of 180'")

    must_revise_chapters:    List[str]
    should_revise_chapters:  List[str]
    optional_chapters:       List[str]

    top_5_micro_topics:      List[str]
    high_risk_clusters:      List[TopicClusterObject] = Field(default_factory=list)

    priority_objects:        List[RevisionPriorityObject] = Field(default_factory=list)
    chapter_summaries:       List[ChapterSummaryObject]  = Field(default_factory=list)

    # SLM-generated strategy text
    executive_summary:  str = ""
    strategy_narrative: str = ""
    exam_brief:         str = ""   # For academic/content team

    insights:           List[InsightObject] = Field(default_factory=list)
    confidence:         float = Field(ge=0.0, le=1.0)
    generated_at:       datetime = Field(default_factory=datetime.utcnow)


# ── Trend Report ───────────────────────────────────────────────────────────────

class TrendShiftReport(BaseModel):
    """
    Documents meaningful changes in topic importance vs previous exam/year.
    Used by exam analysts and content teams.
    """
    report_id:   str
    exam_type:   ExamType
    current_year: int
    compare_year: int   # baseline year

    rising_topics:    List[Dict[str, Any]] = Field(default_factory=list)
    declining_topics: List[Dict[str, Any]] = Field(default_factory=list)
    new_topics:       List[str] = Field(default_factory=list,
        description="Topics appearing for first time in predicted set")
    dropped_topics:   List[str] = Field(default_factory=list)

    trend_narrative:  str = ""
    generated_at:     datetime = Field(default_factory=datetime.utcnow)
